### ISSUE TITLE
Max more than once?

### ISSUE THREAD

**Issue by cmhungsteve** [McGill-NLP/diffusion-itm#3]
After the code is finished running, I got a txt file and one of the results inside is `Max more than once`.
I am curious what it is.
Thank you.

**Comment by BennoKrojer** [comment]
Hi!
It is more for debugging. I noticed that, at least with fp16, sometimes for example the top two ranked candidates would have the same exact score, meaning there is no clear "winner". In general the image-text-scores we get are all very close to each other since the language only plays a minor part for predicting noise.
So I wanted to document how often that happens.
Does that make sense?
Best,
Benno

**Comment by BennoKrojer** [comment]
Thank you for all your interest!
